# NUMPY

Numerical Python- it is built for numerical data
Basic operations
Creating n Reshaping  Numpy arrays
Indexing in Numpy
Statistics
Linear Algebra Operations
Arithmetic Operations
Creating ML models using Numpy(Linear Model)

All models are built with Numpy ,hence all your data has to be numerical when you want to build a model
It helps you create mathematical functions- works better for multidimensional arrays and matrices
You don't need to remember how to build models with 
Numpy--you need mathematical fuctions to help do mathematical operations to help you build models
We have another tool called Scikit-Learn that has inbuilt models--Numpy,SCiPy and Matplotlib

Numpy comes with the anaconda environment therefore you don't need to install it if you have conda installed
You import e.g. import numpy as np

If not installed ,run !pip install numpy

In [1]:
import numpy as np

The Basics
Numpy deals with only one data structure- an array- a list that is supercharged to do intense maths operations

In [4]:
list1=[1,2,3,4,5,6,7,8,9]

convert the type (list) to an array

In [5]:
array1=np.array(list1)

In [6]:
type(array1)

numpy.ndarray

In [7]:
#n-number
#dim-dimension
array1.ndim

1

In [8]:
#size-how many numbers are in your array
array1.size

9

In [9]:
#shape--tuple
array1.shape

(9,)

In [11]:
#dtype-what are the data types of elements in your array
array1.dtype

dtype('int64')

In [12]:
#itemsize-how much space each element occupies
array1.itemsize

8

In [14]:
#total space the array occupies--8x9
array1.nbytes

72

numbers

single whole number-scaler a 0-Dim array e.g. 35
A collection of many numbers (10,14,18,12)-List in python but in math it's called a vector- 1-Dim array

A collection of lists-- a list made of more lists-matrix- 2-Dim array
[[1,2,3,4,5,6,7,8,8,9][10,20,30,40,50,60,70,80,90]]

A collection of tables-tensor- 3-Dim array
[
[[1,2,3,4,5],
[6,7,8,9,10]],

[[2,3,4,5,6],
[3,4,5,6,7]]
]


## Vector- Lists-I Dim array

In [16]:
array2=np.array([1,2,3,4,5])
array2

array([1, 2, 3, 4, 5])

In [18]:
array2.ndim

1

In [20]:
array2.size

5

# Matrix- Tables- 2Dim array

In [22]:
array3=np.array([[1,2,3],[4,5,6]])
array3

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
array3.ndim

2

In [24]:
#2 rows and 3 columns
array3.shape

(2, 3)

# Tensor - List of lists or list of tables- 3Dim array

In [26]:
array4=np.array([
    [[1,2,3], 
     [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ]
])
array4

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [27]:
array4.ndim

3

In [30]:
#2 matrices with 2lists with 3 elements/numbers
array4.shape

(2, 2, 3)

In [31]:
array4.size

12

# Creating a NumPy Array

You can create arrays through, arrange,zeors,ones,random, linspace and eye method

Array method

In [2]:
import numpy as np

In [3]:
twodim=np.array([[2,4,6],[7,8,9],[11,12,13]])
twodim

array([[ 2,  4,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

Arange Method

In [5]:
#creating a range of numbers
#numbers from 1-20
#where should my arrays start for and end + e.g. 1-20 is 1-21
np.arange(0,21)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [4]:
#arange can take a third argument for space between numbers in a range
#you have an arrage of even and odd numbers
np.arange(0,21,7)

array([ 0,  7, 14])

In [6]:
#array of even numbers between 0-20
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
#array of odd numbers between 0-20
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

Zeros Method

In [11]:
zeros=np.zeros(5)
zeros

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

Linspace
the last number will be added in the list
the third argument is how many numbers you want in between a range
It gives the numbers in float and the numbers will have an equal space between them

In [24]:
lin=np.linspace(1,10,4)
lin

array([ 1.,  4.,  7., 10.])

Eye Method
creates an identity matrix which can be used to perform a variety of linear algebra
Identity matrix is  a matrix with zeros across the rows and columns except the diagonal

In [26]:
idn=np.eye(3)
idn

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Random Method- creates random values in an array

In [39]:
#follows a normal distribution 
#most are in a certain range e.g. employee performance 
random=np.random.randn(1,10)
random

array([[ 0.86249777, -0.99753268,  1.73491135,  0.86302552, -0.69558268,
        -1.16283314, -0.64820338,  1.02882038,  1.23549085, -0.67001611]])

In [34]:
random1=np.random.randint(0,100,32)
random1

array([21, 99, 92, 25, 96, 37, 85, 13, 39, 41, 92,  5, 40, 74, 77,  7, 92,
       70, 81,  8, 14, 67, 90, 37, 91, 97, 63, 90, 14, 13, 70, 26])

Reshaping Numpy Array
Changing an array from one shape or dimension to another

In [46]:
nums=np.arange(0,16)
nums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [49]:
#when reshaping the 4x4 must be equal to the total elements in an array
nums2=nums.reshape(4,4)
nums2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
#2x2x5x5 is 100
nums3=np.arange(0,100)
nums4=nums3.reshape(2,2,5,5)
nums4

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]],


       [[[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74]],

        [[75, 76, 77, 78, 79],
         [80, 81, 82, 83, 84],
         [85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94],
         [95, 96, 97, 98, 99]]]])

Flatten makes every other dim array into a vector
It undos reshaping

In [56]:
nums4.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

Statistics--
Computing Mean, Standard Deviation and Variance of a giiven NumPy array

In [70]:
#random seed --saves results of any random operation to memory
#everytime you run the operation you get the same numbers
np.random.seed(23)
random1=np.random.randint(1,100,5)
random1

array([84, 41, 74, 55, 32])

In [71]:
random1=np.random.randint(1,100,5)
random1

array([77, 92, 40, 91, 26])

In [73]:
#argmax -index of max
#argmin -index of min
nom=np.arange(1,17)
nom

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [74]:
nom.mean()

8.5

Idexing 2Dim Array

In [77]:
twodim=np.array([[2,4,6],[7,8,9],[11,12,13]])
twodim

array([[ 2,  4,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [80]:
#getting 2 is index 1, index 1
twodim[0,0]

2

In [81]:
#getting 13 is index 2, index 2
twodim[2,2]

13

In [82]:
twodim[:2]

array([[2, 4, 6],
       [7, 8, 9]])

In [83]:
twodim[0:2]

array([[2, 4, 6],
       [7, 8, 9]])

In [84]:
twodim[1:]

array([[ 7,  8,  9],
       [11, 12, 13]])

In [85]:
twodim[:,2]

array([ 6,  9, 13])

In [86]:
twodim[:,0]

array([ 2,  7, 11])